/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as GraficadoraRouteImport } from './routes/graficadora'
import { Route as EcuacionesRouteImport } from './routes/ecuaciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialIndexRouteImport } from './routes/material/index'
import { Route as MaterialSlugRouteImport } from './routes/material/$slug'

const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const GraficadoraRoute = GraficadoraRouteImport.update({
  id: '/graficadora',
  path: '/graficadora',
  getParentRoute: () => rootRouteImport,
} as any)
const EcuacionesRoute = EcuacionesRouteImport.update({
  id: '/ecuaciones',
  path: '/ecuaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIndexRoute = MaterialIndexRouteImport.update({
  id: '/material/',
  path: '/material/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialSlugRoute = MaterialSlugRouteImport.update({
  id: '/material/$slug',
  path: '/material/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecuaciones': typeof EcuacionesRoute
  '/graficadora': typeof GraficadoraRoute
  '/reportar': typeof ReportarRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/material/': typeof MaterialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecuaciones': typeof EcuacionesRoute
  '/graficadora': typeof GraficadoraRoute
  '/reportar': typeof ReportarRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/material': typeof MaterialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecuaciones': typeof EcuacionesRoute
  '/graficadora': typeof GraficadoraRoute
  '/reportar': typeof ReportarRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/material/': typeof MaterialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecuaciones'
    | '/graficadora'
    | '/reportar'
    | '/material/$slug'
    | '/material/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecuaciones'
    | '/graficadora'
    | '/reportar'
    | '/material/$slug'
    | '/material'
  id:
    | '__root__'
    | '/'
    | '/ecuaciones'
    | '/graficadora'
    | '/reportar'
    | '/material/$slug'
    | '/material/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcuacionesRoute: typeof EcuacionesRoute
  GraficadoraRoute: typeof GraficadoraRoute
  ReportarRoute: typeof ReportarRoute
  MaterialSlugRoute: typeof MaterialSlugRoute
  MaterialIndexRoute: typeof MaterialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graficadora': {
      id: '/graficadora'
      path: '/graficadora'
      fullPath: '/graficadora'
      preLoaderRoute: typeof GraficadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecuaciones': {
      id: '/ecuaciones'
      path: '/ecuaciones'
      fullPath: '/ecuaciones'
      preLoaderRoute: typeof EcuacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/': {
      id: '/material/'
      path: '/material'
      fullPath: '/material/'
      preLoaderRoute: typeof MaterialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug': {
      id: '/material/$slug'
      path: '/material/$slug'
      fullPath: '/material/$slug'
      preLoaderRoute: typeof MaterialSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcuacionesRoute: EcuacionesRoute,
  GraficadoraRoute: GraficadoraRoute,
  ReportarRoute: ReportarRoute,
  MaterialSlugRoute: MaterialSlugRoute,
  MaterialIndexRoute: MaterialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
